### ISSUE TITLE
[Nei append issuess]asset_bg item repeated loaded or not loaded

### ISSUE THREAD

**Issue by TTOSND** [Pain-Brioche/COM3D2.MaidLoader#1]
BepInEx 5.4.21.0
COM3D2 2.23.0

test mod:森の道(Twitter→@ykprsrm_game)  repeated loaded  https://ux.getuploader.com/com3d2_mod_kyouyu_d/
城下町っぽい背景(Twitter→@ykprsrm_game)  not loaded  https://ux.getuploader.com/com3d2_mod_kyouyu_f/
川岸(Twitter→@ykprsrm_game)  repeated loaded  https://ux.getuploader.com/com3d2_mod_kyouyu_e/
image:https://upload.cc/i1/2022/10/18/I2FPri.png https://upload.cc/i1/2022/10/18/jrn75F.png

**Comment by Pain-Brioche** [comment]
Sory, not used to check the issue report on github, I'll have a look :)

**Comment by Pain-Brioche** [comment]
Both issues are fixed.
https://upload.cc/i1/2022/10/23/4zxOlr.jpg
Thanks again.
