### ISSUE TITLE
Shedule scv data error when specific files in Mod dir

### ISSUE THREAD

**Issue by TokcDK** [Pain-Brioche/COM3D2.MaidLoader#3]
Tried to use the loader. Main menu loaded very fast like no mods was loaded.
When tried to load game from last save got the error:
![2022-12-23_113955](https://user-images.githubusercontent.com/5264340/209286379-facf549b-a031-436d-a146-47e8436a2ddb.png)
Then checked new game(because I know that without some plugins exist save cant be loaded) and all was fine but after first dialog of selecting 1st maid I got almost the same error (even more detailed):
![2022-12-23_110821](https://user-images.githubusercontent.com/5264340/209286920-323b92b8-470e-4ff4-9fe9-b17e85669a03.png)

with old modloader no kind of errors

upd. while was writing it, found dir which causing the errors when in Mod dir:
[VIP_MOD_200912_2.zip](https://github.com/Pain-Brioche/COM3D2.MaidLoader/files/10294311/VIP_MOD_200912_2.zip)

The loader is killing my ancient cpu but makes the game loading much faster. 

_It would be good also resolve a issue with memory management when in chara editor game can consume a lot of memory 10+gb ram when many mods is in Mod folder(70+gb of modfiles in my case). But this is an other story._

**Comment by Pain-Brioche** [comment]
I'll have a look, thanks for the report :)

**Comment by Pain-Brioche** [comment]
Finally looked at this.
This mod uses .ks and .arc to work; .arc loading from the mod folder is disabled by default for performance reasons.
You can enable it back in MaidLoader's config to see if it fixes the issue.

**Comment by TokcDK** [comment]
changed .arc loading to true and added folder again but still see same errors and cant load saves.

**Comment by Pain-Brioche** [comment]
I'm still pretty bad at fixing stuff in due time.
However I found a bug that might be related to this issue.

I'll push a new release soon

**Comment by Pain-Brioche** [comment]
Latest 1.2.3 will hopefully fix this.

**Comment by TokcDK** [comment]
It seems there is no error now. Thank you!
